In [1]:
from ingest import load_faq_data
documents = load_faq_data()

In [2]:
docs_llm = [doc for doc in documents if doc['course'] == 'llm-zoomcamp']
len(docs_llm)

118

In [4]:
from sqlitesearch import TextSearchIndex

index = TextSearchIndex(
    text_fields=['question', 'section', 'answer'],
    keyword_fields=['course'],
    id_field='doc_id',      # <-- use the existing id so if it's re-run, it will update existing records instead of creating duplicates
    db_path='faq.db'
)

In [5]:
import time

for doc in docs_llm:
    doc['doc_id'] = doc.pop('id') # "id" is already a reserved column in sqlite, need to add the ids from the json as a different field name
    index.add(doc)
    print(f'Added: {doc["question"][:60]}...')
    time.sleep(0.5)

Added: I just discovered the course. Can I still join?...
Added: Course: I have registered for the LLM Zoomcamp. When can I e...
Added: What is the video/zoom link to the stream for the “Office Ho...
Added: How should I start the course and follow the weekly workflow...
Added: Leaderboard: I am not on the leaderboard / how do I know whi...
Added: Certificate: Can I follow the course in a self-paced mode an...
Added: I missed the first homework - can I still get a certificate?...
Added: Homework: Why does the content keep changing?...
Added: When will the course be offered next?...
Added: Are there any lectures/videos? Where are they?...
Added: Where can I track the LLM Zoomcamp syllabus, deadlines, home...
Added: Are there live sessions or office hours for each module?...
Added: Can I use Bluesky for learning in public credits?...
Added: Where is the LLM Zoomcamp Telegram channel?...
Added: Why doesn't the number of records I get in the FAQ dataset m...
Added: The homework submission form is still open even though the d...
Added: Can I submit homework after the deadline, or get a deadline ...
Added: Will the name I put in the certificate field be shown public...
Added: Why are we not using Langchain in the course?...
Added: OpenAI: Error when running OpenAI responses.create command...
Added: OpenAI: Error: RateLimitError: Error code: 429 -...
Added: OpenAI: How much will I have to spend to use the Open AI API...
Added: OpenAI: Do I have to subscribe and pay for Open AI API for t...
Added: Why use uv package/project manager instead of the more tradi...
Added: Authentication: Why is my OPENAI_API_KEY not found in the Ju...
Added: How to store and load API keys using .env file...
Added: Can I use a model or provider different from the one recomme...
Added: How do I start using Google Gemini models in the Module 1 no...
Added: How can I get structured output (Pydantic objects) from Gemi...
Added: Ollama: How to install Ollama?...
Added: Connection refused error when prompting Ollama RAG...
Added: OpenAI: Why does my token count differ from what OpenAI repo...
Added: API keys: how do I set them once and not re-export every ter...
Added: How should I choose field weights for minsearch or another s...
Added: How should I prepare documents for RAG?...
Added: uv says Failed to hardlink files in Codespaces. Is it an err...
Added: dotenv is not recognized. What should I install?...
Added: Can I run the course locally instead of Codespaces?...
Added: What happens to code saved in Codespaces if I do not commit ...
Added: WSL2: ResponseError: model requires more system memory (X.X ...
Added: My Codespace won't reconnect (stuck on "Finishing up") or my...
Added: Do I have to use OpenAI, or can I use a different provider?...
Added: How do I avoid hitting OpenAI rate limits (429 errors) durin...
Added: What are tools and functions in agentic RAG?...
Added: Any free models with tool use support?...
Added: Agents: "AttributeError: 'str' object has no attribute 'outp...
Added: I am using Azure OpenAI and I am still getting an error of E...
Added: toyaikit: how do I use it with a non-OpenAI provider (e.g. G...
Added: Where can I find the homework questions?...
Added: Homework: Returning Empty list after filtering my query (HW ...
Added: OpenRouter: Error code 402 when calling responses.create (ma...
Added: What does it mean to point RAG at the chunk index in Module ...
Added: Do homework answers need to match the options exactly?...
Added: What should I do if homework questions feel unclear?...
Added: How do I get token counts for Module 1 homework if I use a d...
Added: My homework submission is rejected because my repo URL retur...
Added: What are embeddings?...
Added: Warning: 'model "multi-qa-mpnet-base-dot-v1" was made on sen...
Added: Why was .dot(...) used directly to compute cosine similarity...
Added: Vector search: should I embed the question, the answer, or b...
Added: What is the cosine similarity?...
Added: Why does cosine similarity reduce to a matrix multiplication...
Added: Do I need a new GitHub repo for Module 2, or just a new code...
Added: Why does download.py hang at 0% when downloading model.onnx ...
Added: Why do the matrix and for-loop versions of vector search giv...
Added: Why do I get IndexError: list index out of range when access...
Added: My Module 2 homework cosine similarity (Q2) isn't any of the...
Added: How do I configure the Gemini (and OpenAI/Tavily) API keys f...
Added: Kestra AI Copilot replies "I can only assist with creating K...
Added: I set SECRET_GEMINI_API_KEY but my Kestra flow still fails w...
Added: Why do we need orchestration / Kestra — can't I just run the...
Added: Is Kestra mandatory for the LLM Zoomcamp course, or can I us...
Added: Which AI providers does Kestra support besides Gemini? Can I...
Added: Can I use Kestra without writing any code? Is there a no-cod...
Added: Why does a generic AI assistant generate Kestra flow YAML wi...
Added: Why is token usage monitored in Kestra workflows?...
Added: How do I fix the Docker error 'mounts denied: The path /tmp/...
Added: Kestra: Gemini model returns 404 or is unavailable. What do ...
Added: What do I submit for the Module 3 (Kestra) homework? Everyth...
Added: Evaluation: "JSONDecodeError: Expecting value" when generati...
Added: Evaluation: Jupyter kernel crashes when embedding the ground...
Added: Evaluation: hitting rate limits while generating the ground-...
Added: Why is there a gap between lessons 6 and 11 in Module 4?...
Added: Why can MRR improve while Hit Rate stays the same?...
Added: In Windows OS: OSError: [WinError 126] The specified module ...
Added: OperationalError when running python prep.py: psycopg2. Oper...
Added: How set Pandas to show entire text content in a column. Usef...
Added: How to normalize vectors in a Pandas DataFrame column (or Pa...
Added: How to compute the quantile or percentile of Pandas DataFram...
Added: How can I remove all Docker containers, images, and volumes,...
Added: Session State: I want the user to only be able to give feedb...
Added: How do I adapt RAGWithMetrics for a provider such as Gemini ...
Added: Docker: When trying to run a streamlit app using docker-comp...
Added: Is it a group project?...
Added: Do we submit 2 projects, what does attempt 1 and 2 mean?...
Added: Does the competition count as the capstone?...
Added: How is my capstone project going to be evaluated?...
Added: When and how will we be assigned projects for review/grading...
Added: I’ve already submitted my project. Why can’t I review any pr...
Added: How can I find some good ideas or datasets for the project?...
Added: Project: do I need an orchestration tool (Airflow, Mage, Kes...
Added: Project: how do I evaluate a recommender-style RAG (no obvio...
Added: Project: my corpus is large (long PDFs, many paragraphs). Wh...
Added: Project: what does "reproducibility" mean — do reviewers nee...
Added: Can I use a programming language other than Python (for exam...
Added: Where can I find previous LLM Zoomcamp projects?...
Added: Do I need to announce or reserve my project idea?...
Added: Can I use WhatsApp, Telegram, or some other interface for my...
Added: What can I use to extract text from PDFs (or scanned/OCR doc...
Added: Can I use the workshop materials for my own projects or shar...
Added: How to set up a new dlt project when loading from cloud?...
Added: There is an error when opening the table using `dbtable = db...
Added: There is an error when running main(): FileNotFoundError: Ta...
Added: How do I know which tables are in the db?...
Added: Does DLT have connectors to ClickHouse or StarRocks?...
Added: Notebook does not have secret access or 401 Client Error: Un...
Added: Error: How to fix requests library only installs v2.28 inste...
Added: Why does my EU-region Logfire token return 401 Unauthorized?...

### sqlite data

In [33]:
import sqlite3
import pandas as pd

In [ ]:
pd.set_option('display.max_columns', None)  # Show all columns
from IPython.display import display, clear_output

In [39]:
def read_sqlite_db(db_path: str):
    # Connect to the database file
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row  # allows accessing columns by name
    cur = conn.cursor()

    try:
        # Get a list of all user tables
        cur.execute("""
            SELECT name
            FROM sqlite_master
            WHERE type = 'table'
              AND name NOT LIKE 'sqlite_%'
            ORDER BY name
        """)
        tables = [row[0] for row in cur.fetchall()]

        for table in tables:
            print(f"Reading table: {table}, number of rows: {cur.execute(f'SELECT COUNT(*) FROM \"{table}\"').fetchone()[0]}")
            print(f"Columns: {[desc[0] for desc in cur.execute(f'SELECT * FROM \"{table}\"').description]}")

            df =pd.read_sql_query(f'SELECT * FROM "{table}" LIMIT 5', conn).head()  # Display first 5 rows using pandas
            display(df)

            print()

    finally:
        conn.close()

In [40]:
read_sqlite_db('faq.db')

Reading table: docs, number of rows: 118
Columns: ['id', 'doc_json', 'vector_hash', 'course', 'doc_id']

,id,doc_json,vector_hash,course,doc_id
0,1,"{""course"": ""llm-zoomcamp"", ""section"": ""General...",None,llm-zoomcamp,74eb249bbf
1,2,"{""course"": ""llm-zoomcamp"", ""section"": ""General...",None,llm-zoomcamp,977bf7786c
2,3,"{""course"": ""llm-zoomcamp"", ""section"": ""General...",None,llm-zoomcamp,489dd1c9d9
3,4,"{""course"": ""llm-zoomcamp"", ""section"": ""General...",None,llm-zoomcamp,04919992b3
4,5,"{""course"": ""llm-zoomcamp"", ""section"": ""General...",None,llm-zoomcamp,c2903069a0

Reading table: docs_fts, number of rows: 118
Columns: ['docid', 'question', 'section', 'answer']

,docid,question,section,answer
0,1,I just discovered the course. Can I still join?,General Course-Related Questions,"Yes, but if you want to receive a certificate,..."
1,2,Course: I have registered for the LLM Zoomcamp...,General Course-Related Questions,You don't need it. You're accepted. You can al...
2,3,What is the video/zoom link to the stream for ...,General Course-Related Questions,The zoom link is only published to instructors...
3,4,How should I start the course and follow the w...,General Course-Related Questions,Start with the [LLM Zoomcamp docs](https://dat...
4,5,Leaderboard: I am not on the leaderboard / how...,General Course-Related Questions,"When you set up your account, you are automati..."

Reading table: docs_fts_config, number of rows: 1
Columns: ['k', 'v']

         k  v
0  version  4

Reading table: docs_fts_content, number of rows: 118
Columns: ['id', 'c0', 'c1', 'c2', 'c3']

,id,c0,c1,c2,c3
0,1,1,I just discovered the course. Can I still join?,General Course-Related Questions,"Yes, but if you want to receive a certificate,..."
1,2,2,Course: I have registered for the LLM Zoomcamp...,General Course-Related Questions,You don't need it. You're accepted. You can al...
2,3,3,What is the video/zoom link to the stream for ...,General Course-Related Questions,The zoom link is only published to instructors...
3,4,4,How should I start the course and follow the w...,General Course-Related Questions,Start with the [LLM Zoomcamp docs](https://dat...
4,5,5,Leaderboard: I am not on the leaderboard / how...,General Course-Related Questions,"When you set up your account, you are automati..."

Reading table: docs_fts_data, number of rows: 27
Columns: ['id', 'block']

             id                                              block
0             1                         b'vv\x8dG\x83\x0f\xd8\x1e'
1            10  b'\x00\x00\x00\x00\x03\nv\x00\x06\x02\x01\x01\...
2  137438953473  b'\x00\x00\x0f\x0f\x0200\x1c\x08\x01\x03\x81\x...
3  137438953474  b'\x00\x00\x0f\'\x080awesome\x17\x06\x01\x031\...
4  137438953475  b'\x00\x06\x0f\n\x03C*\x08\x01\x03\x82\n\x07\x...

Reading table: docs_fts_docsize, number of rows: 118
Columns: ['id', 'sz']

   id                       sz
0   1        b'\x01\t\x04\x15'
1   2         b'\x01\x11\x04*'
2   3         b'\x01\x11\x04R'
3   4         b'\x01\x0b\x04t'
4   5  b'\x01\x12\x04\x81\x05'

Reading table: docs_fts_idx, number of rows: 25
Columns: ['segid', 'term', 'pgno']

   segid         term  pgno
0      1          b''     2
1      1      b'0awe'     4
2      1     b'0date'     6
3      1  b'0generat'     8
4      1    b'0keepi'    10